### PR TITLE
Combine tasks and convert to OOP

### PR DESCRIPTION
**Pull request by zero-nnkn**
- [x] Combine tasks in one file (support sub command)
- [x] Convert code to OOP 
- [x] Update `README.md`

### CODE REVIEW

**Comment by egliette** [comment]
```python
content = requests.get(f"https://vnexpress.net/{article_type}-p{i}").content
```  
 
This [line](https://github.com/Zero-nnkn/VNExpressCrawler/blob/d2184bad9ca0ebbbbfb7aba9176f313f23de3556/utils/bs4_utils.py#L68) needs to be changed or included in the VNExpressCrawler class for OOP purposes

**Comment by zero-nnkn** [comment]
@egliette Ok, I'm sorry I missed it. I think we should include it inside VNExpressCrawler for the purpose of expanding more news sites later. Then we just create crawlers depending on the type passed in (something like factory). I will make a little modification to take advantage of Factory.

**Comment by zero-nnkn** [comment]
@egliette, I made some changes to apply the factory pattern in this situation. Now can extend to more news websites in the future by adding to `crawler/factory.py`.
Please review and let me know if something is wrong.

**Comment by zero-nnkn** [comment]
Hey, I made some fixes to the list of supported websites and updated the doc.

**Comment by egliette** [comment]
Very good! Thanks for your improvements.

**Comment by zero-nnkn** [comment]
Thank you, I hope you will develop the project to support crawling more news sites.

**Pull request merged**
